routes/web.php
<?php

use App\Slider;
use App\Category;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	$sliders=Slider::orderBy('created_at','DESC')->get();
    return view('frontend.index',compact('sliders'));
});

Route::get('/about-us', function () {
    return view('frontend.about-us');
});
Route::get('/contact', function () {
    return view('frontend.contact');
});

Route::get('/products/{id}', function ($id) {
	$category=Category::find($id);
    return view('frontend.products',compact('category'));
})->name('products');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::group(['prefix'=>'admin','middleware'=>'auth'], function(){

	Route::get('/home','HomeController@index');
	Route::get('/logout','Auth\LoginController@logout')->name('logout');
	Route::post('/logout','Auth\LoginController@logout')->name('logout');
	Route::resource('mother-category','MotherCategoryController');
	Route::get('/mother-category/delete/{id}','MotherCategoryController@delete')->name('mother-category.delete');

	Route::resource('category','CategoryController');
	Route::get('/category/delete/{id}','CategoryController@delete')->name('category.delete');

	Route::get('image/showSpecific/','ImageController@showSpecific')->name('image.show.specific');
	Route::get('image/delete/{id}','ImageController@delete')->name('image.del');
	Route::resource('image','ImageController');

	Route::get('/slider/delete/{id}','SliderController@delete')->name('slider.delete');
	Route::resource('slider','SliderController');
	
});

resources/views/admin/ShowAllProduct-image.blade.php
@extends('admin.layouts.master')
@section('content')
<div class="row ">
	<div class="col-md-1"></div>
	<div class="col-md-10">
		<div class="card m-t-80">
			<div class="card-title">
				<h4>All Image </h4>
			</div>
			<div class="card-body">
				<div class="table-responsive">
					<table class="table table-hover ">
						<thead>
							<tr>
								<th>#</th>
								<th>Image</th>
								<th>Action</th>
							</tr>
						</thead>
						<tbody>
							@foreach($images as $index => $image)
							<tr>
								<th scope="row">{{$index+1}}</th>
								<td class="color-primary"><img height="100" width="100" src="{{asset('images/uploaded/'.$image->name)}}" alt=""></td>
								<td class="color-primary">
									<a id="deleteBtn" data-id="{{$image->id}}" href="#" style="color: white;" class="btn btn-danger btn-outline m-b-10 m-l-5 btn-xs"><i class="fa fa-trash-o"></i></a>
								</td>
							</tr>
							@endforeach
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
	<div class="col-md-1"></div>
</div>
@endsection
@section('script')
	<script>
		$(document).on('click', '#deleteBtn', function(el) {
		var postId = $(this).data("id");
		swal({
			title: "Are you sure?",
			text: "Once deleted, you will not be able to recover this imaginary file!",
			icon: "warning",
			buttons: true,
			dangerMode: true,
		})
		.then((willDelete) => {
		if (willDelete) {
				swal("Deleting...", {
				icon: "success",
			});
			window.location.href = window.location.href = "image/delete/" + postId;
				}
			});
		});
	</script>
@endsection

resources/views/admin/add-category.blade.php
@extends('admin.layouts.master')
@section('content')
<div class="row ">
	<div class="col-md-3"></div>
	<div class="col-md-6">
		<div class="card m-t-80">
			<div class="card-title">
				<h4>Add a Category</h4>
			</div>
			<div class="card-body">
				<div class="basic-form">
					<form action="{{route('category.store')}}" method="post">
						@csrf
						<div class="form-group">
							<label class="m-t-20" for="">Mother Category name : </label>
							<div class="input-group input-group-flat">
								<span class="input-group-btn" style="height: 30px;"><span class="btn btn-primary btn-disabled" ><i class="ti-search"></i></span></span>
								<select name="mCId" class="form-control" required>
									<option value="" selected="" disabled="">--Select a Mother Category--</option>
									@foreach($mCategories as $category)
									<option value="{{$category->id}}">{{$category->name}}</option>
									@endforeach
								</select>
								
							</div>
							<label class="m-t-40" for="">Category name :</label>
							<div class="input-group input-group-flat">
								<span class="input-group-btn"><span class="btn btn-primary btn-disabled" type="submit"><i class="ti-search"></i></span></span>
								<input type="text" name="category" class="form-control" placeholder="add a category" required="">
								
							</div>
							<div class="input-group input-group-flat m-t-30">
								<input type="submit" class="btn btn-success form-control" placeholder="add a category">
								
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	<div class="col-md-3"></div>
</div>
<div class="row ">
	<div class="col-md-1"></div>
	<div class="col-md-10">
		<div class="card m-t-80">
			<div class="card-title">
				<h4>All Categories </h4>
			</div>
			<div class="card-body">
				<div class="table-responsive">
					<table class="table table-hover ">
						<thead>
							<tr>
								<th>#</th>
								<th>Name</th>
								<th>Action</th>
							</tr>
						</thead>
						<tbody>
							@foreach($categories as $index => $category)
							<tr>
								<th scope="row">{{$index+1}}</th>
								<td class="color-primary">{{$category->name}}</td>
								<td class="color-primary">
									<a style="color: white;" href="{{route('category.edit',$category->id)}}" class="btn btn-info btn-outline m-b-10 m-l-5 btn-xs"><i class="fa fa-edit"></i></a>
									<a id="deleteBtn" data-id="{{$category->id}}" href="#" style="color: white;" class="btn btn-danger btn-outline m-b-10 m-l-5 btn-xs"><i class="fa fa-trash-o"></i></a>
								</td>
							</tr>
							@endforeach
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
	<div class="col-md-1"></div>
</div>
@endsection
@section('script')
<script>
    $(document).on('click', '#deleteBtn', function(el) {
        var postId = $(this).data("id");

        swal({
          title: "Are you sure?",
          text: "Once deleted, you will not be able to recover this imaginary file!",
          icon: "warning",
          buttons: true,
          dangerMode: true,
        })
        .then((willDelete) => {
          if (willDelete) {
            swal("Deleting...", {
              icon: "success",
            });
            window.location.href = window.location.href = "category/delete/" + postId;
          } 
        });

    });
</script>
@endsection

resources/views/admin/add-image.blade.php
@extends('admin.layouts.master')
@section('content')
<style>
	select.form-control:not([size]):not([multiple]) {
    /* height: calc(2.25rem + 2px); */
    height: 43px;
}
</style>
<div class="row">
	<div class="col-md-2"></div>
	<div class="col-md-8">
		<div class="card m-t-80">
			<div class="card-title">
				<h4>Add a Image</h4>
			</div>
			<div class="card-body">
				<div class="basic-form">
					<form action="{{ route('image.store') }}" method="post" enctype="multipart/form-data">
						@csrf
						<div class="form-group">
							<div class="input-group input-group-flat m-t-20">
								<span class="input-group-btn"><span class="btn btn-primary btn-disabled" ><i class="ti-search"></i></span></span>
								<select name="catId" class="form-control" required="">
									<option value="" selected="" disabled="">--Select a Category--</option>
									@foreach($categories as $category)
									<option value="{{$category->id}}">{{$category->name}}</option>
									@endforeach
								</select>
								
							</div>
							
							<div class="input-group input-group-flat m-t-20">
								<span class="input-group-btn"><span class="btn btn-primary btn-disabled"><i class="ti-search"></i></span></span>
								<input type="file" id="uploadFile" name="uploadFile[]" class="form-control" required="" multiple>
							</div>
							
							<div class="input-group input-group-flat m-t-30">
								<input type="submit" class="btn btn-success form-control" name='submitImage' value="Upload Image">
								
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	<div class="col-md-2"></div>
</div>


<div class="row">
	<div class="col-md-2"></div>
	<div class="col-md-8">
		<div id="image_preview"></div>
	</div>
	<div class="col-md-2"></div>
</div>






{{-- <div class="container">

  <h1>Laravel Ajax Multiple Image Upload with Preview Example</h1>

  <form action="{{ route('image.store') }}" method="post" enctype="multipart/form-data">

      {{ csrf_field() }}

      <input type="file" id="uploadFile" name="uploadFile[]" multiple/>

      <input type="submit" class="btn btn-success" name='submitImage' value="Upload Image"/>

  </form>



  <br/>

  <div id="image_preview"></div>

</div> --}}
@endsection

@section('script')


<script type="text/javascript">



  $("#uploadFile").change(function(){

     $('#image_preview').html("");

     var total_file=document.getElementById("uploadFile").files.length;

     for(var i=0;i<total_file;i++)

     {

      $('#image_preview').append("<img style='margin:5px; height:200px;width:231px;border:1px solid #cacaca' src='"+URL.createObjectURL(event.target.files[i])+"'>");

     }

  });



  // $('form').ajaxForm(function() 

  //  {

  //   alert("Uploaded SuccessFully");

  //  }); 



</script>
@endsection

resources/views/admin/add-mother-category.blade.php
@extends('admin.layouts.master')
@section('content')
<div class="row ">
	<div class="col-md-3"></div>
	<div class="col-md-6">
		<div class="card m-t-80">
			<div class="card-title">
				<h4>Add a Mother Category</h4>
			</div>
			<div class="card-body">
				<div class="basic-form">
					<form action="{{route('mother-category.store')}}" method="post">
						@csrf
						<div class="form-group">
							
							<div class="input-group input-group-flat">
								<span class="input-group-btn"><span class="btn btn-primary btn-disabled" type=""><i class="ti-search"></i></span></span>
								<input type="text" name="name" class="form-control" placeholder="add a mother category" required="">
								
							</div>
							<div class="input-group input-group-flat m-t-30">
								<input type="submit" class="btn btn-success form-control" placeholder="add a category">
								
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	<div class="col-md-3"></div>
</div>
<div class="row">
	<div class="col-md-2"></div>
	<div class="col-md-8">
		<div class="card m-t-20">
			<div class="card-title">
				<h4> Mother Category List</h4>
			</div>
			<div class="card-body">
		<table class="table">
			<thead>
				<tr>
					<th scope="col">#</th>
					<th scope="col">Name</th>
					<th scope="col">Action</th>
				</tr>
			</thead>
			<tbody>
				@foreach($categories as $index => $category)
				<tr>
					<td>{{$index+1}}</td>
					<td>{{$category->name}}</td>
					<td>
						<a href="{{route('mother-category.edit',$category->id)}}" style="color: white;" class="btn btn-info btn-outline m-b-10 m-l-5 btn-xs"><i class="fa fa-pencil"></i></a>
						<a id="deleteBtn" data-id="{{$category->id}}" href="#" style="color: white;" class="btn btn-danger btn-outline m-b-10 m-l-5 btn-xs"><i class="fa fa-trash-o"></i></a>
					</td>
				</tr>
				@endforeach
			</tbody>
		</table>
	</div></div></div></div>
	<div class="col-md-2"></div>
</div>
@endsection

@section('script')
<script>
    $(document).on('click', '#deleteBtn', function(el) {
        var postId = $(this).data("id");

        swal({
          title: "Are you sure?",
          text: "Once deleted, you will not be able to recover this imaginary file!",
          icon: "warning",
          buttons: true,
          dangerMode: true,
        })
        .then((willDelete) => {
          if (willDelete) {
            swal("Deleting...", {
              icon: "success",
            });
            window.location.href = window.location.href = "mother-category/delete/" + postId;
          } 
        });

    });
</script>
@endsection

resources/views/admin/add-slider.blade.php
@extends('admin.layouts.master')
@section('content')
<div class="row ">
	<div class="col-md-2"></div>
	<div class="col-md-8">
		<div class="card m-t-80">
			<div class="card-title">
				<h4>Add a Slider</h4>
			</div>
			<div class="card-body">
				<div class="basic-form">
					<form action="{{ route('slider.store') }}" method="post" enctype="multipart/form-data">
						@csrf
						<div class="form-group">
							
							<div class="input-group input-group-flat m-t-20">
								<span class="input-group-btn"><span class="btn btn-primary btn-disabled"><i class="ti-search"></i></span></span>
								<input type="file" id="uploadFile" name="uploadFile[]" class="form-control" required="" multiple>
							</div>
							
							<div class="input-group input-group-flat m-t-30">
								<input type="submit" class="btn btn-success form-control" name='submitImage' value="Upload Image">
								
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	<div class="col-md-2"></div>
</div>

<div class="row">
	<div class="col-md-2"></div>
	<div class="col-md-8">
		<div id="image_preview"></div>
	</div>
	<div class="col-md-2"></div>
</div>
@endsection

@section('script')


<script type="text/javascript">



  $("#uploadFile").change(function(){

     $('#image_preview').html("");

     var total_file=document.getElementById("uploadFile").files.length;

     for(var i=0;i<total_file;i++)

     {

      $('#image_preview').append("<img style='margin:5px; height:200px;width:231px;border:1px solid #cacaca' src='"+URL.createObjectURL(event.target.files[i])+"'>");

     }

  });

</script>
@endsection

resources/views/admin/edit-category.blade.php
@extends('admin.layouts.master')
@section('content')
<div class="row ">
	<div class="col-md-3"></div>
	<div class="col-md-6">
		<div class="card m-t-80">
			<div class="card-title">
				<h4>Edit Category</h4>
			</div>
			<div class="card-body">
				<div class="basic-form">
					<form action="{{route('category.update',$category->id)}}" method="post">
						@csrf
						{{ method_field('PUT') }}
						<div class="form-group">
							<label class="m-t-20" for="">Mother Category</label>
							<div class="input-group input-group-flat ">

								<span class="input-group-btn" style="height: 30px;"><span class="btn btn-primary btn-disabled" ><i class="ti-search"></i></span></span>
								<select name="mCId" class="form-control">
									<option value="" disabled="">--Select a Mother Category--</option>
									@foreach($mCategories as $mCategory)
									<option {{$mCategory->id==$category->id?'selected':''}} value="{{$mCategory->id}}">{{$mCategory->name}}</option>
									@endforeach
								</select>
								
							</div>
							<label class="m-t-40" for="">Category</label>
							<div class="input-group input-group-flat ">
								<span class="input-group-btn"><span class="btn btn-primary btn-disabled" type="submit"><i class="ti-search"></i></span></span>
								<input type="text" name="category" class="form-control" placeholder="add a category" required="" value="{{$category->name}}">
								
							</div>
							<div class="input-group input-group-flat m-t-30">
								<input type="submit" class="btn btn-success form-control" placeholder="add a category">
								
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	<div class="col-md-3"></div>
</div>
@endsection

resources/views/admin/edit-mother-category.blade.php
@extends('admin.layouts.master')
@section('content')
<div class="row ">
	<div class="col-md-3"></div>
	<div class="col-md-6">
		<div class="card m-t-80">
			<div class="card-title">
				<h4>Edit Mother Category</h4>
			</div>
			<div class="card-body">
				<div class="basic-form">
					<form action="{{route('mother-category.update',$category->id)}}" method="post">
						@csrf
						{{ method_field('PUT') }}
						<div class="form-group">
							
							<div class="input-group input-group-flat">
								<span class="input-group-btn"><span class="btn btn-primary btn-disabled" type="submit"><i class="ti-search"></i></span></span>
								<input type="text" name="name" class="form-control" placeholder="add a category" required="" value="{{$category->name}}">
								
							</div>
							<div class="input-group input-group-flat m-t-30">
								<input type="submit" class="btn btn-success form-control" placeholder="add a category">
								
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	<div class="col-md-3"></div>
</div>
@endsection

resources/views/admin/index.blade.php
@php
$sliders=App\Slider::orderBy('created_at','DESC')->get();
@endphp

@extends('admin.layouts.master')
@section('content')
<div class="row ">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <div class="tz-gallery">
            <h2 class="text-center">Showing "Sliders"</h2>
            <div class="row">
                @foreach($sliders as $image)
                <div class="animated  col-sm-12 col-md-6">
                    <div style="margin: 10px;">
                        <a class="lightbox" href="{{asset('images/slider/'.$image->name)}}">
                        <img src="{{asset('images/slider/'.$image->name)}}" alt="Park">
                    </a>
                    <a id="deleteBtn" data-id="{{$image->id}}" style="margin-top: -30px;" href="" class="btn btn-block btn-danger">Delete</a>
                    </div>
                    
                </div>
                @endforeach
                
            </div>
        </div>
        <div class="col-md-1"></div>
    </div>
</div>
@endsection

@section('script')
<script>
    $(document).on('click', '#deleteBtn', function(el) {
        el.preventDefault();
        var postId = $(this).data("id");

        swal({
          title: "Are you sure?",
          text: "Once deleted, you will not be able to recover this imaginary file!",
          icon: "warning",
          buttons: true,
          dangerMode: true,
        })
        .then((willDelete) => {
          if (willDelete) {
            swal("Deleting...", {
              icon: "success",
            });
            window.location.href = window.location.href = "slider/delete/" + postId;
          } 
        });

    });
</script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.js"></script>
<script>
baguetteBox.run('.tz-gallery');
</script>
@endsection

resources/views/admin/show-image.blade.php
@extends('admin.layouts.master')
@section('content')
<style>
	select.form-control:not([size]):not([multiple]) {
    /* height: calc(2.25rem + 2px); */
    height: 43px;
}
</style>
<div class="row">
	<div class="col-md-2"></div>
	<div class="col-md-8">
		<div class="card m-t-80">
			<div class="card-title">
				<h4>Select specific category to show image!</h4>
			</div>
			<div class="card-body">
				<div class="basic-form">
					<form action="{{ route('image.show.specific') }}" method="get" enctype="multipart/form-data">
						@csrf
						<div class="form-group">
							<div class="input-group input-group-flat m-t-20">
								<span class="input-group-btn"><span class="btn btn-primary btn-disabled" ><i class="ti-search"></i></span></span>
								<select name="catId" class="form-control" required="">
									<option value="" selected="" disabled="">--Select a Category--</option>
									@foreach($categories as $category)
									<option value="{{$category->id}}">{{$category->name}}</option>
									@endforeach
								</select>
								
							</div>
							
							<div class="input-group input-group-flat m-t-30">
								<input type="submit" class="btn btn-success form-control" name='submitImage' value="Select Category to show Image">
								
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	<div class="col-md-2"></div>
</div>

@endsection

@section('script')

@endsection

resources/views/admin/showAll-image.blade.php
@extends('admin.layouts.master')
@section('content')
<div class="row ">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <div class="tz-gallery">
            <h2 class="text-center">Showing "{{$category->name}}"</h2>
            <div class="row">
                @foreach($images as $image)
                <div class="animated  col-sm-6 col-md-4">
                    <div style="margin: 10px;">
                        <a class="lightbox" href="{{asset('images/products/'.$image->name)}}">
                        <img src="{{asset('images/products/'.$image->name)}}" alt="Park">
                    </a>
                    <a id="deleteBtn" data-id="{{$image->id}}" style="margin-top: -30px;" href="" class="btn btn-block btn-danger">Delete</a>
                    </div>
                    
                </div>
                @endforeach
                
            </div>
        </div>
        <div class="col-md-1"></div>
    </div>
</div>
@endsection
@section('script')
<script>
$(document).on('click', '#deleteBtn', function(el) {
    el.preventDefault();
    var postId = $(this).data("id");
    swal({
      title: "Are you sure?",
      text: "Once deleted, you will not be able to recover this imaginary file!",
      icon: "warning",
      buttons: true,
      dangerMode: true,
    })
    .then((willDelete) => {
      if (willDelete) {
        swal("Deleting...", {
          icon: "success",
        });
        window.location.href = window.location.href = "delete/" + postId;
      }
    });
});
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.js"></script>
<script>
baguetteBox.run('.tz-gallery');
</script>
@endsection

resources/views/admin/showAll-slider.blade.php
@extends('admin.layouts.master')
@section('content')
<div class="row ">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <div class="tz-gallery">
            <h2 class="text-center">Showing "Sliders"</h2>
            <div class="row">
                @foreach($sliders as $image)
                <div class="animated  col-sm-12 col-md-6">
                    <div style="margin: 10px;">
                        <a class="lightbox" href="{{asset('images/slider/'.$image->name)}}">
                        <img src="{{asset('images/slider/'.$image->name)}}" alt="Park">
                    </a>
                    <a id="deleteBtn" data-id="{{$image->id}}" style="margin-top: -30px;" href="" class="btn btn-block btn-danger">Delete</a>
                    </div>
                    
                </div>
                @endforeach
                
            </div>
        </div>
        <div class="col-md-1"></div>
    </div>
</div>
@endsection

@section('script')
<script>
    $(document).on('click', '#deleteBtn', function(el) {
        el.preventDefault();
        var postId = $(this).data("id");

        swal({
          title: "Are you sure?",
          text: "Once deleted, you will not be able to recover this imaginary file!",
          icon: "warning",
          buttons: true,
          dangerMode: true,
        })
        .then((willDelete) => {
          if (willDelete) {
            swal("Deleting...", {
              icon: "success",
            });
            window.location.href = window.location.href = "slider/delete/" + postId;
          } 
        });

    });
</script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.js"></script>
<script>
baguetteBox.run('.tz-gallery');
</script>
@endsection